/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RAHUL
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        Lusername = new javax.swing.JLabel();
        Tusername = new javax.swing.JTextField();
        Lpassword = new javax.swing.JLabel();
        Tpassword = new javax.swing.JPasswordField();
        Bsignin = new javax.swing.JButton();
        Label2 = new javax.swing.JLabel();
        Bsignup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        Label1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        Label1.setForeground(new java.awt.Color(255, 0, 255));
        Label1.setText("COMPANY");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(Label1)
                .addGap(39, 39, 39))
        );

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOG IN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 204, 204))); // NOI18N

        Lusername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lusername.setForeground(new java.awt.Color(255, 255, 0));
        Lusername.setText("Username :");

        Tusername.setBackground(new java.awt.Color(51, 51, 51));
        Tusername.setForeground(new java.awt.Color(255, 255, 255));
        Tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TusernameActionPerformed(evt);
            }
        });
        Tusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TusernameKeyReleased(evt);
            }
        });

        Lpassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lpassword.setForeground(new java.awt.Color(255, 255, 0));
        Lpassword.setText("Password :");

        Tpassword.setBackground(new java.awt.Color(51, 51, 51));
        Tpassword.setForeground(new java.awt.Color(255, 255, 255));
        Tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TpasswordActionPerformed(evt);
            }
        });
        Tpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TpasswordKeyReleased(evt);
            }
        });

        Bsignin.setBackground(new java.awt.Color(51, 51, 51));
        Bsignin.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Bsignin.setForeground(new java.awt.Color(255, 255, 0));
        Bsignin.setText("SIGN IN");
        Bsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsigninActionPerformed(evt);
            }
        });

        Label2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Label2.setForeground(new java.awt.Color(255, 255, 102));
        Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label2.setText("Not a member?");

        Bsignup.setBackground(new java.awt.Color(51, 51, 51));
        Bsignup.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Bsignup.setForeground(new java.awt.Color(255, 255, 0));
        Bsignup.setText("SING UP");
        Bsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsignupActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("");
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel1KeyReleased(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lusername)
                            .addComponent(Lpassword))
                        .addGap(18, 18, 18)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tusername, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(Tpassword)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Label2)
                        .addGap(20, 20, 20)
                        .addComponent(Bsignup))
                    .addComponent(Bsignin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lusername)
                    .addComponent(Tusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lpassword)
                    .addComponent(Tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Bsignin)
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label2)
                    .addComponent(Bsignup))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TusernameActionPerformed

    private void BsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsignupActionPerformed
       SignUpForm ref = new SignUpForm();
       ref.setVisible(true);
       ref.pack();
       ref.setLocationRelativeTo(null);
       ref.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_BsignupActionPerformed

    private void BsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsigninActionPerformed
        if(Tusername.getText().trim().isEmpty() && Tpassword.getText().trim().isEmpty())
        {
            jLabel1.setText("Username is empty");
            jLabel2.setText("Password is empty");
        }
        else if(Tusername.getText().trim().isEmpty())
        {
            jLabel1.setText("Username is empty");           
        }
        else if(Tpassword.getText().trim().isEmpty()){
            jLabel2.setText("Password is empty");
        }
        else
        {
            /*try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","pass");
                
                
            Statement st=con.createStatement();
            ResultSet rs;
            String strSQL = "select count(*) from user_details where username='" + Tusername.getText().trim() + "' and password = '" + Tpassword.getText().trim() + "'";
            rs = st.executeQuery(strSQL);
            rs.next();*/
            try
            {
            ResultSet rs = null;
            Connection con = ConnectDB.getConnection();
            Statement st = con.createStatement();
            String strSQL = "select count(*) from user_details where username='" + Tusername.getText().trim() + "' and password = '" + Tpassword.getText().trim() + "'";
            rs = st.executeQuery(strSQL);
            rs.next();
            if(rs.getInt(1)==1)
            {
                GlobalVariables gv = GlobalVariables.getinstance();
                gv.setUsername(Tusername.getText().trim());
                try
                {
                ResultSet rs2 = null;
                Connection con2 = ConnectDB.getConnection();
                Statement st2 = con2.createStatement();
                String strSQL2 = "select id,name from user_details where username='" + Tusername.getText().trim() + "'";
                rs2 = st2.executeQuery(strSQL2);
                rs2.next(); 
                gv.setUserid(rs2.getInt(1));
                gv.setName(rs2.getString(2));
                }
                catch(Exception e){
                  jLabel2.setText("username or password is invalid");   
                }
            Welcome w =new Welcome();
            w.setVisible(true);
            w.pack();
            w.setLocationRelativeTo(null);
            this.dispose();
            }
            else
            {
               jLabel2.setText("username or password is invalid"); 
            }
            }
            
            catch(Exception e)
            {
                jLabel2.setText("username or password is invalid"+e.getMessage());
                //JFrame jF2=new JFrame();
                //JOptionPane.showMessageDialog(jF2,e.getMessage());
                //JOptionPane.showMessageDialog(jF2,e.getStackTrace());
                
            }
            
        }        
    }//GEN-LAST:event_BsigninActionPerformed

    private void TusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TusernameKeyReleased
        jLabel1.setText("");
    }//GEN-LAST:event_TusernameKeyReleased

    private void TpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TpasswordActionPerformed

    private void TpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TpasswordKeyReleased
        jLabel2.setText("");
    }//GEN-LAST:event_TpasswordKeyReleased

    private void jLabel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsignin;
    private javax.swing.JButton Bsignup;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Lpassword;
    private javax.swing.JLabel Lusername;
    private javax.swing.JPasswordField Tpassword;
    private javax.swing.JTextField Tusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables

}
