
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author RAHUL
 */
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistorForm
     */
    public SignUpForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        Panel = new javax.swing.JPanel();
        Lname = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        Ldob = new javax.swing.JLabel();
        Laddress = new javax.swing.JLabel();
        Lmail = new javax.swing.JLabel();
        Tmail = new javax.swing.JTextField();
        Lphone = new javax.swing.JLabel();
        Tphone = new javax.swing.JTextField();
        Lusername = new javax.swing.JLabel();
        Tusername = new javax.swing.JTextField();
        Lpassword = new javax.swing.JLabel();
        Lcpassword = new javax.swing.JLabel();
        Bsignup = new javax.swing.JButton();
        Tpassword = new javax.swing.JPasswordField();
        Tcpassword = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Taddress = new javax.swing.JTextArea();
        Tdob = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(0, 0, 0));
        Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SIGNUP", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 204, 204))); // NOI18N

        Lname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lname.setForeground(new java.awt.Color(255, 255, 0));
        Lname.setText("Name* :");

        Tname.setBackground(new java.awt.Color(51, 51, 51));
        Tname.setForeground(new java.awt.Color(255, 255, 255));

        Ldob.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Ldob.setForeground(new java.awt.Color(255, 255, 0));
        Ldob.setText("Date Of Birth* :");

        Laddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Laddress.setForeground(new java.awt.Color(255, 255, 0));
        Laddress.setText("Address* :");

        Lmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lmail.setForeground(new java.awt.Color(255, 255, 0));
        Lmail.setText("Email-id* :");

        Tmail.setBackground(new java.awt.Color(51, 51, 51));
        Tmail.setForeground(new java.awt.Color(255, 255, 255));
        Tmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TmailActionPerformed(evt);
            }
        });
        Tmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TmailKeyReleased(evt);
            }
        });

        Lphone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lphone.setForeground(new java.awt.Color(255, 255, 0));
        Lphone.setText("Mobile* :");

        Tphone.setBackground(new java.awt.Color(51, 51, 51));
        Tphone.setForeground(new java.awt.Color(255, 255, 255));
        Tphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TphoneActionPerformed(evt);
            }
        });

        Lusername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lusername.setForeground(new java.awt.Color(255, 255, 0));
        Lusername.setText("Username* :");

        Tusername.setBackground(new java.awt.Color(51, 51, 51));
        Tusername.setForeground(new java.awt.Color(255, 255, 255));
        Tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TusernameActionPerformed(evt);
            }
        });

        Lpassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lpassword.setForeground(new java.awt.Color(255, 255, 0));
        Lpassword.setText("Password* :");

        Lcpassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lcpassword.setForeground(new java.awt.Color(255, 255, 0));
        Lcpassword.setText("Confirm Password* :");

        Bsignup.setBackground(new java.awt.Color(51, 51, 51));
        Bsignup.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Bsignup.setForeground(new java.awt.Color(255, 255, 0));
        Bsignup.setText("Sign Up");
        Bsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsignupActionPerformed(evt);
            }
        });

        Tpassword.setBackground(new java.awt.Color(51, 51, 51));
        Tpassword.setForeground(new java.awt.Color(255, 255, 255));
        Tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TpasswordActionPerformed(evt);
            }
        });
        Tpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TpasswordKeyReleased(evt);
            }
        });

        Tcpassword.setBackground(new java.awt.Color(51, 51, 51));
        Tcpassword.setForeground(new java.awt.Color(255, 255, 255));
        Tcpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcpasswordActionPerformed(evt);
            }
        });

        Taddress.setBackground(new java.awt.Color(51, 51, 51));
        Taddress.setColumns(10);
        Taddress.setForeground(new java.awt.Color(255, 255, 255));
        Taddress.setRows(5);
        jScrollPane2.setViewportView(Taddress);

        Tdob.setBackground(new java.awt.Color(204, 204, 204));
        Tdob.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ldob)
                    .addComponent(Lname)
                    .addComponent(Lmail)
                    .addComponent(Lphone)
                    .addComponent(Lusername)
                    .addComponent(Lpassword)
                    .addComponent(Lcpassword)
                    .addComponent(Laddress))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tphone)
                    .addComponent(Tmail)
                    .addComponent(Tusername)
                    .addComponent(Tcpassword)
                    .addComponent(jScrollPane2)
                    .addComponent(Tpassword)
                    .addComponent(Tname)
                    .addComponent(Tdob, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(Bsignup))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname)
                    .addComponent(Tname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ldob)
                    .addComponent(Tdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Laddress)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lmail)
                    .addComponent(Tmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lphone)
                    .addComponent(Tphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lusername)
                    .addComponent(Tusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lpassword)
                    .addComponent(Tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lcpassword)
                    .addComponent(Tcpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Bsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Bsignup.getAccessibleContext().setAccessibleDescription("");
        Tdob.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TusernameActionPerformed

    private void TpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TpasswordActionPerformed
    
    }//GEN-LAST:event_TpasswordActionPerformed

    private void BsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsignupActionPerformed
        String s = Tmail.getText();
        char c ;
        int mail_count = 0,count_Uname=0;
        try
        {
            ResultSet res_set = null;
            Connection con1= ConnectDB.getConnection();
            Statement st=con1.createStatement();
            String strSQL1 = "(select count(*) from user_details where username = '" + Tusername.getText().trim() + "')";
            res_set = st.executeQuery(strSQL1);
            res_set.next();
            count_Uname = res_set.getInt(1);
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
        
        for(int i=0;i<s.length();i++)
        {
            c=s.charAt(i);
            if(c == '@'){
               mail_count++; 
            }
            else if(c == '.'){
                mail_count++;
            }
        }
        boolean b;
        b = Pattern.matches("[789]{1}[0-9]{9}",Tphone.getText());
        if(Tname.getText().trim().isEmpty() || Taddress.getText().trim().isEmpty() || Tmail.getText().trim().isEmpty() || Tphone.getText().trim().isEmpty() || Tusername.getText().trim().isEmpty() || Tpassword.getText().trim().isEmpty() || Tcpassword.getText().trim().isEmpty()){
            jLabel1.setText("Please fill all details");
        }
        else if(mail_count != 2){
            jLabel1.setText("Enter valid email");
        }
        else if(!b){
            jLabel1.setText("Inavlid Mobile No.");
        }
        else if(count_Uname != 0)
        {
            jLabel1.setText("Username already Exists");
        }
        else if(!Tpassword.getText().equals(Tcpassword.getText())){
            jLabel1.setText("Passsword's does not match");           
        }
        
        else{
             try
            {
                /*Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull","root","pass");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(Tdob.getDate());  
            
                
            Statement st=con.createStatement();
            ResultSet rs;
            rs=st.executeQuery("(select max(id) from user_details)");
            rs.next();*/
            ResultSet rs = null;
            Connection con= ConnectDB.getConnection();
            Statement st=con.createStatement();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(Tdob.getDate()); 
            String strSQL1 = "(select max(id) from user_details)";
            rs = st.executeQuery(strSQL1);
            rs.next();
            int nextid = rs.getInt(1)+1;
            String strSQL2 = "insert into user_details values( '" + nextid + "','" + Tname.getText().trim() + "','" + date + "','" + Taddress.getText() + "','" + Tmail.getText() + "','" + Tphone.getText() + "','" + Tusername.getText() + "','" + Tpassword.getText() + "')";
            st.executeUpdate(strSQL2);
            
            LoginForm lf_fromsignup = new LoginForm();
            lf_fromsignup.setVisible(true);
            lf_fromsignup.setLocationRelativeTo(null);
            lf_fromsignup.pack();
            dispose();
            
            }
            catch(Exception e)
            {
                    System.out.println(e.getMessage());
                    e.printStackTrace();
            }
            
          
        }
    }//GEN-LAST:event_BsignupActionPerformed

    private void TcpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcpasswordActionPerformed

    private void TpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TpasswordKeyReleased
        jLabel1.setText("");
    }//GEN-LAST:event_TpasswordKeyReleased

    private void TmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TmailActionPerformed

    private void TmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TmailKeyReleased
        jLabel1.setText("");
    }//GEN-LAST:event_TmailKeyReleased

    private void TphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TphoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoginForm lf_fromSignup = new LoginForm();
        lf_fromSignup.setVisible(true);
        lf_fromSignup.pack();
        lf_fromSignup.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsignup;
    private javax.swing.JLabel Laddress;
    private javax.swing.JLabel Lcpassword;
    private javax.swing.JLabel Ldob;
    private javax.swing.JLabel Lmail;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel Lpassword;
    private javax.swing.JLabel Lphone;
    private javax.swing.JLabel Lusername;
    private javax.swing.JPanel Panel;
    private javax.swing.JTextArea Taddress;
    private javax.swing.JPasswordField Tcpassword;
    private com.toedter.calendar.JDateChooser Tdob;
    private javax.swing.JTextField Tmail;
    private javax.swing.JTextField Tname;
    private javax.swing.JPasswordField Tpassword;
    private javax.swing.JTextField Tphone;
    private javax.swing.JTextField Tusername;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
